// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepCrime.LawEnforcement.DATA.Context;

#nullable disable

namespace RepCrime.LawEnforcement.DATA.Migrations
{
    [DbContext(typeof(RepCrimeLawEnforcementContext))]
    [Migration("20221024133421_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RepCrime.LawEnforcement.DATA.Models.AssignCrime", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("LawEnforcementEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LawEnforcementEntityId");

                    b.ToTable("AssignCrimes");
                });

            modelBuilder.Entity("RepCrime.LawEnforcement.DATA.Models.LawEnforcementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LawEnforcements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("220029c5-c7ed-4d9d-b173-5e846a06b9dd"),
                            Rank = 2
                        },
                        new
                        {
                            Id = new Guid("18d9ee8a-ff1b-4e26-b0df-e621c12a6334"),
                            Rank = 0
                        },
                        new
                        {
                            Id = new Guid("ef031c7f-b012-4af6-bb0b-8a456accc226"),
                            Rank = 1
                        });
                });

            modelBuilder.Entity("RepCrime.LawEnforcement.DATA.Models.AssignCrime", b =>
                {
                    b.HasOne("RepCrime.LawEnforcement.DATA.Models.LawEnforcementEntity", "LawEnforcementEntity")
                        .WithMany("AssignedCrimes")
                        .HasForeignKey("LawEnforcementEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawEnforcementEntity");
                });

            modelBuilder.Entity("RepCrime.LawEnforcement.DATA.Models.LawEnforcementEntity", b =>
                {
                    b.Navigation("AssignedCrimes");
                });
#pragma warning restore 612, 618
        }
    }
}
